language: php
matrix:
    include:
        - php: 7.1
        - php: 7.2

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer --verbose install

script:
  - phpunit --version
      